name: telegrambot
description: Library to implement a Telegram Bot.
version: 0.1.1-dev

authors:
- Roel Spilker <r.spilker@gmail.com>

homepage: https://github.com/TOPdesk/dart-telegrambot
documentation:

environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  http_client: ^0.3.0

dev_dependencies:
  test: ^0.12.0
